name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Package backend (skip tests)
        working-directory: back-costa
        run: ./mvnw -q -DskipTests package

      - name: Verify backend
        working-directory: back-costa
        run: ./mvnw verify

  frontend:
    name: Frontend build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: front-costa/package-lock.json

      - name: Install dependencies
        working-directory: front-costa
        run: npm ci

      - name: Build frontend
        working-directory: front-costa
        run: npm run build
